euros:
  - Testu Test parent
  - Mohassane Naima
  - Mari Virginie
  - Briere Pierre
  - Dif Amel
  - Ayache Stephanie
  - Louispicco Christel
  - Nikitina Anna
  - Forgione Agata
  - Denielle
  - Calabresi Aurélie
  - Tessier Carole
  - Thiam Fatou

